helmDefaults:
  skipDeps: true # skip running "helm repo update" and "helm dependency build"
---

environments:
  example:
    values: 
    - ./environments/example/values.yaml

releases:
  - name: etcd-backup
    namespace: kube-system
    chart: ./chart
    historyMax: 3
    values:
      - ./chart/values.yaml
      - ./environments/{{ .Environment.Name }}/values.yaml